[package]
name = "adventofcode-2019"
version = "0.1.0"
authors = ["Emil Lundberg <emil@emlun.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
